language: python
python:
  - "2.7"
before_install:
  # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq


# command to install dependencies
install: 
  - pip install -r requirements.txt
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform

# command to run tests
script: 
  - nosetests --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_slpkg_df6916b6be_2
  - python -m properform Push 47.88.50.110:15554 asdf_slpkg_df6916b6be_2 ./profile_slpkg_df6916b6be_2
#2017-08-08 19:10:57 modified at 0#2017-08-08 19:11:04 modified at 1#2017-08-08 19:11:10 modified at 2