language: python
python:
  - "2.7"
before_install:
  # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq


# command to install dependencies
install: 
  - pip install -r requirements.txt
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform

# command to run tests
script: 
  - nosetests --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_slpkg_fb5e7e68d6_3
  - python -m properform Push 47.88.50.110:15554 asdf_slpkg_fb5e7e68d6_3 ./profile_slpkg_fb5e7e68d6_3
#2017-08-08 17:35:33 modified at 0#2017-08-08 17:35:39 modified at 1#2017-08-08 17:35:47 modified at 2#2017-08-08 17:35:54 modified at 3