language: python
python:
  - "2.7"
before_install:
  # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq


# command to install dependencies
install: 
  - pip install -r requirements.txt
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform

# command to run tests
script: 
  - nosetests --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_slpkg_4bd55133e1_3
  - python -m properform Push 47.88.50.110:15554 asdf_slpkg_4bd55133e1_3 ./profile_slpkg_4bd55133e1_3
#2017-08-08 18:49:42 modified at 0#2017-08-08 18:49:53 modified at 1#2017-08-08 18:50:03 modified at 2#2017-08-08 18:50:10 modified at 3